default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /var/lib/mysql/mysql.sock

development:
  <<: *default
  database: muscle-habits_development

test:
  <<: *default
  database: muscle-habits_test

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  pool: 5